const main = async () => {
    try {
        console.log('main');
    } catch (error) {
        console.error(error);
    }
}

main();
